### ISSUE TITLE
Would this be easily adaptable to Vue.js?  

### ISSUE THREAD

**Issue by vonwao** [IjzerenHein/firestorter#77] opened 2019-04-18 00:21 UTC
It seems that they are similar in many ways.  I haven't seen MobX mentioned much in the Vue community, but I imagine you still need something like this.  Am I right?

**Comment by IjzerenHein** [comment] 2019-04-19 09:18
Duplicate of #25

**Comment by IjzerenHein** [comment] 2019-04-19 09:18
Closing, lets continue the discussion in the other thread

**Closed by IjzerenHein** 2019-04-19 09:18 UTC
Labels: duplicate
